### PR TITLE
Move and improve If-None-Match: * tests

### PR DESCRIPTION
**Pull request by kjetilk**
This moves some converted tests into the main tests, links to the spec, and improves them. 

I commented out the spec#341 relevant tests

### CODE REVIEW

**Review by edwardsph — APPROVED** [review]
LGTM
One thing I am going to change on all tests (so if you wanted to get ahead you could do it now) is to use properties instead of get methods, so:
`* def requestUri = resource.url`

**Comment by kjetilk** [comment]
Alright! Like this, or does it influence other functions too?

**Comment by edwardsph** [comment]
Sorry I wasn't thorough enough - any getter on containers and resources: getUrl(), getAclUrl(), getContainer() so you can also have testContainer.url

**Comment by kjetilk** [comment]
So, like this, I guess?

**Comment by edwardsph** [comment]
Perfect!

**Pull request merged**
